name: Set Up Release NPM and PyPI
description: Set up NPM and PyPI for release

runs:
  using: 'composite'
  steps:
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.SEMANTIC_RELEASE_APP_ID }}
        private_key: ${{ secrets.SEMANTIC_RELEASE_PRIVATE_KEY }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ steps.generate_token.outputs.token }}

    - uses: ./.github/actions/setup-monorepo

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ vars.NXCACHE_IAM_ROLE }}
        aws-region: ${{ vars.NXCACHE_AWS_REGION }}
        role-session-name: NxCache

    - name: git config
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      shell: bash
      run: |
        git remote rm origin
        git remote add origin https://vm-x-ai:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        git symbolic-ref HEAD refs/heads/main
        git config --global push.autoSetupRemote true
        git config user.name "vm-x-ai-release[bot]"
        git config user.email "167465110+vm-x-ai-release[bot]@users.noreply.github.com"

    - name: npm config
      shell: bash
      run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: poetry config
      shell: bash
      run: poetry config pypi-token.pypi "$PYPI_TOKEN"
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
