[tool.coverage.run]
branch = true
source = [ "vmxai" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-report html:'../../../coverage/packages/sdk/python/html' --cov-report xml:'../../../coverage/packages/sdk/python/coverage.xml' --html='../../../reports/packages/sdk/python/unittests/html/index.html' --junitxml='../../../reports/packages/sdk/python/unittests/junit.xml'"

[tool.poetry]
name = "vm-x-ai-sdk"
version = "1.2.0"
description = "VM-X AI Python SDK"
authors = [ "VM-X Engineering <eng@vm-x.ai>" ]
maintainers = [ "VM-X Engineering <eng@vm-x.ai>" ]
license = "MIT"
readme = "README.md"
repository = "https://github.com/vm-x-ai/vm-x-ai-sdk"
keywords = [ "VM-X", "AI", "SDK", "Python" ]
classifiers = [
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3"
]
group = { }

  [[tool.poetry.packages]]
  include = "vmxai"

  [tool.poetry.dependencies]
  python = ">=3.8,<4"
  requests = "^2.31.0"
  cachetools = "^5.3.3"
  grpcio = "^1.62.2"
  protobuf = "^4.21.6"

    [tool.poetry.dependencies.vm-x-ai-completion-client]
    path = "../../completion/client/python"
    develop = true

[tool.ruff]
exclude = [
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "dist",
  "vmxai/protos"
]
line-length = 120
indent-width = 4

  [tool.ruff.lint]
  select = [ "E", "F", "UP", "B", "SIM", "I" ]
  ignore = [ ]
  fixable = [ "ALL" ]
  unfixable = [ ]

[build-system]
requires = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"
