name: Pull Request Checks

on:
  pull_request:

jobs:
  checks:
    name: Checks
    uses: vm-x-ai/github-public-actions/.github/workflows/workflow-pull-request.yml@main
    secrets: inherit
    with:
      use-python: true
