name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

permissions:
  actions: write
  id-token: write
  pull-requests: write
  issues: write
  statuses: write
  checks: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-release
      - name: Release
        run: |
          pnpm nx release --yes
          git push --follow-tags
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
