name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

permissions:
  actions: write
  id-token: write
  pull-requests: write
  issues: write
  statuses: write
  checks: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.SEMANTIC_RELEASE_APP_ID }}
          private_key: ${{ secrets.SEMANTIC_RELEASE_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - uses: ./.github/actions/setup-monorepo
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.NXCACHE_IAM_ROLE }}
          aws-region: ${{ vars.NXCACHE_AWS_REGION }}
          role-session-name: NxCache

      - name: Release
        run: |
          poetry config pypi-token.pypi "$PYPI_TOKEN"
          pnpm nx affected -t release --parallel=false
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          HUSKY: '0'
